version: '2'
services:
  front:
    build: .
    ports:
      - "5000:80"
      - "5443:444"
      - "9001:9000"
    volumes:
      - ./code:/code
    depends_on:
      - mongo
  mongo:
    image: mongo
