version: '2'
services:
  front:
    build: docker-front
    ports:
      - "5080:80"
      - "5443:443"
    volumes:
      - ./code:/code
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./code/data/db:/data/db
